### ISSUE TITLE
Angular in MVC conventions

### ISSUE THREAD

**Issue by sebakerckhof** [awatson1978/meteor-cookbook#57]
I was reading this article: https://github.com/awatson1978/meteor-cookbook/blob/master/cookbook-conventions.md

And it puts both angular, nodejs and ruby in the server-side MVC camp. But I fail to see how Angular fits the server-side MVC model, being a client-side only library build especially with the purpose of building single-page client side applications...

**Comment by awatson1978** [comment]
The Meteor Cookbook is written with the browser (Firefox, Chrome, etc) as the client-side MVC model.  Which makes Angular part of the server-side MVC model, since it's delivered to the browser by the server.  

If you think of Angular simply as 'client-side' code, you're fundamentally mis-understanding some of the core architecture of how web-browsers and and HTTP servers work.  Don't just think in terms of the client/server code that resides on the server.  Consider the compiled browser that interprets the code as well.  

I recommend referencing the [W3C standards](http://www.w3.org/standards/), and  spending a decade or so doing thick-client application development using a compiled language (such as WinForms or Object-C) that has direct access to the operating systems double-buffered graphics pipeline, and it will begin to make a bit more sense.

**Comment by giantelk** [comment]
I disagree. AngularJS HTML/templates may be render-able server side, but
the premise of AngularJS is the same as SpaceBars/HandleBars i.e. single
page web app.

AngularJS is all JavaScript with HTML. It simplifies AJAX in the browser,
it's designed from the ground up to be rendered client side. There's been
lots of blog talk over the past 1-2 years about how hard it is to render
AngularJS server side (maybe that's fixed in the latest ver?).

AngularJS can be used with Meteor as the backend. But AngularJS provide no
backend feature on it's own. i.e. most AngularJS apps use Express/Node in
the back end.

Does that make sense? Here's the Wikipedia description:

...framework for client-side model–view–controller
<http://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller> (MVC)
architecture, along with components commonly used in rich internet
applications <http://en.wikipedia.org/wiki/Rich_Internet_Application>.

http://en.wikipedia.org/wiki/AngularJS


On Fri, Feb 27, 2015 at 12:43 PM, Abigail Watson <notifications@github.com>
wrote:

> Closed #57 <https://github.com/awatson1978/meteor-cookbook/issues/57>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awatson1978/meteor-cookbook/issues/57#event-243429479>
> .
>



-- 

Cheers,
*Flying Horse Dancing*

**Comment by awatson1978** [comment]
That's nice that you disagree.  Feel free to write your own cookbook and explain the technology however you'd like.  I've been programming for 30 years, and have seen this issue crop up before with X-Windows, and think the current crop of so-called "Web MVC" frameworks are fundamentally misguided.  And the movement towards WebComponents backs up my position.  We're just going to have to agree to disagree.  Best.

**Comment by giantelk** [comment]
I think most people would agree with this: the current crop of so-called
"Web MVC" frameworks are fundamentally misguided.

I'm just stating the facts, AngularJS is client side only. No AngularJS
code runs on the server. It's client side MVC, which is very confusing to
people learning MVC, as with MEAN stack, you also have to implement server
side MC in Express. So yes it's a messy haystack!

On Fri, Feb 27, 2015 at 1:26 PM, Abigail Watson <notifications@github.com>
wrote:

> That's nice that you disagree. Feel free to write your own cookbook and
> explain the technology however you'd like. I've been programming for 30
> years, and have seen this issue crop up before with X-Windows, and think
> the current crop of so-called "Web MVC" frameworks are fundamentally
> misguided. And the movement towards WebComponents backs up my position.
> We're just going to have to agree to disagree. Best.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awatson1978/meteor-cookbook/issues/57#issuecomment-76445597>
> .
>



-- 

Cheers,
*Flying Horse Dancing*

**Comment by sebakerckhof** [comment]
> Which makes Angular part of the server-side MVC model, since it's delivered to the browser by the server.If you think of Angular simply as 'client-side' code, you're fundamentally mis-understanding some of the core architecture of how web-browsers and and HTTP servers work.

Well, as somebody who has contributed code to the apache HTTP server, I believe I understand how a http server works quite well. Any web application is delivered to the browser by a server. How else? Meteor apps are delivered in the exact same fashion, but once delivered they run mostly client-side, just like Angular. And for that matter, angular is even less server-side compatible than blaze.

I'm sorry you fail to see this after 30 years of programming.

**Comment by awatson1978** [comment]
Look, as far as I'm concerned, the "View" in MVC is reserved for what gets written to the video buffer and blasted at a person's eyeballs.  Anything rendered within that UIWebView isn't part of the local client compiled code.  It's a interpreted workflow component (nowdays called a WebComponent) that is compiled to DOM, not to a BMP file.  And that interpreted code, while not processed on the server, is structured and stored on the server.  More specifically, it's an MVC pattern that's stored on the server.  Not in a browser extension.  As far as I'm concerned, the interpreted code is a server-side MVC pattern, even if it's executed on the client.  

I agree that Meteor apps are delivered in the exact same fashion as Angular, and my criticism extends to Blaze as well.  I was quite relieved that Blaze 2 is going to move towards the Component namespace, and recognize that there are multiple MVC models in use in the ecosystem.  Regardless of the nomenclature, javascript will continue to be run on the client-side as interpreted code, not as native compiled code.   And as long as there's a UIWebView or similar sandbox, the javascript doesn't have access to the operating system's double-buffered graphics pipeline; thus isn't part of the native client-side MVC model.  At least not as far as I'm concerned.

Listen, I decided to write the Meteor Cookbook with a focus on browser MVC structure, since I spent a great deal of time working in radiology departments and animation studios working with high-resolution monitors, stereographic monitors, quad buffered graphics pipelines, animation rendering clusters, and the like.  We were very particular about our graphics pipeline, and what MVC meant with regard to the video buffer.  And it's my prerogative to write the book how I wish.  If I wish to discuss MVC models with a focus on the video graphics pipeline and make a distinction between interpreted/compiled code, rather than ignoring those differences, that's my prerogative to do so.

I encourage you to write your own cookbook.  Since you contributed code to the apache HTTP server, you are obviously capable.   In the meantime, please respect the fact that I may have a different understanding of these technologies than you do; and that I may be taking into consideration different components of the technology stack as I design my applications and write tutorials.  Thank you and good day.

**Comment by sebakerckhof** [comment]
I fail to see what low level concepts as compilation vs interpretation and the graphics pipeline have to do with a high level pattern on structuring your application (MVC). That this renders to DOM, which in turn the browser transforms in something it can feed into the rasterization pipeline, is for me a matter of separation of concerns. But I do agree that you are free to look at this the way you want and write the cookbook the way you want.

However, I posted this issue because of this sentence out of your cookbook:
"Isomorphic javascript requires that the Meteor community reconciles the server-side MVC patterns used by the Rubyists, Node.js folks, and Angular folks, with the client-side thick-client MVC patterns used by WinForm, .NET, Unity, and Flash developers." This just doesn't make any sense, even considering your previous post.
